version: '3.7'

services:
  app:
    image: ghcr.io/mvoreichental/website
    build: .
    hostname: app
    restart: unless-stopped
    depends_on:
      - mysql
    networks:
      - network
    ports:
      - '8080:80'
    volumes:
      - ./data:/app/data

  mysql:
    image: mariadb
    hostname: mysql
    restart: unless-stopped
    networks:
      - network
    volumes:
      - mysql:/var/lib/mysql
      - ./src/main/resources/database.sql:/docker-entrypoint-initdb.d/database.sql:ro
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'true'
      MYSQL_DATABASE: mvo
      MYSQL_USER: mvo
      MYSQL_PASSWORD: mvo

networks:
  network:

volumes:
  mysql: